services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: energypac
      DB_USER: root
      DB_PASSWORD: ""
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    env_file:
      - .env
    restart: unless-stopped
